### ISSUE TITLE
create footer section and add all social media of our community.

### ISSUE THREAD

**Issue by aayusranjan** [codingbrunches/codingBrunch-community#11]
[Twitter](https://twitter.com/codingbrunch)
[Discord](https://discord.gg/ThfAbN5ms9)
[Instagram](https://www.instagram.com/codingbrunch/)

**Comment by rafaelaqueirozg** [comment]
Hey, I would like to do this. Can you assign it to me, please?

**Comment by aayusranjan** [comment]
Sure @rafaelaqueirozg
